spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test_db_1
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true